"""
SQLAlchemy ORM model for the `accounts` table. This is the Python
representation of a row.

Note: the column types here must match the migration (0001_initial_schema.py)
exactly. SQLAlchemy does NOT enforce this; you have to keep them in sync
by hand. If they drift, you get runtime errors when reading/writing.

For autogenerated migrations we'd use SQLAlchemy's declarative metadata
as the source of truth and run `alembic revision --autogenerate`. We chose
hand-written migrations (see NOTES.md). The trade-off is occasional
manual sync work like this.
"""
from datetime import datetime

from sqlalchemy import JSON, TIMESTAMP, Boolean, String, Text, text
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    """Base class for all ORM models. Required by SQLAlchemy 2.0."""

    pass


class Account(Base):
    __tablename__ = "accounts"

    id: Mapped[str] = mapped_column(Text, primary_key=True)
    customer_id: Mapped[str] = mapped_column(Text, nullable=False)
    currency: Mapped[str] = mapped_column(String(3), nullable=False)
    status: Mapped[str] = mapped_column(
        Text, nullable=False, server_default="pending"
    )
    livemode: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("false")
    )
    metadata_json: Mapped[dict] = mapped_column(
        JSON, nullable=False, server_default="{}"
    )
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, server_default=text("NOW()")
    )
    updated_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, server_default=text("NOW()")
    )
